# Generated by Django 5.2.6 on 2025-10-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='DNI/Identificación')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('descripcion', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Interno')),
                ('stock_actual', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo del Técnico')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('serie_imei', models.CharField(help_text='Clave única para identificar el equipo.', max_length=100, unique=True, verbose_name='Nro. Serie / IMEI')),
                ('modelo', models.CharField(help_text='Ej. iPhone 12, XPS 13', max_length=100, verbose_name='Modelo')),
                ('accesorios', models.TextField(blank=True, verbose_name='Accesorios Entregados')),
                ('estado_general', models.TextField(blank=True, verbose_name='Estado General y Estético')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_servicios.marca', verbose_name='Marca')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_servicios.tipoequipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado (Pendiente de Asignar)'), ('PRESUPUESTADO', 'Presupuesto Enviado'), ('EN_ESPERA_REP', 'En Espera de Repuestos'), ('EN_REPARACION', 'En Reparación'), ('TERMINADA', 'Reparación Terminada (Listo para Entregar)'), ('NO_REPARABLE', 'No Reparable'), ('ENTREGADA', 'Entregado al Cliente')], default='INGRESADO', max_length=20, verbose_name='Estado Actual')),
                ('falla_reportada', models.TextField(verbose_name='Falla Reportada por el Cliente')),
                ('informe_tecnico', models.TextField(blank=True, verbose_name='Diagnóstico e Informe Técnico')),
                ('mano_de_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Mano de Obra')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo a Cobrar')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones_cliente', to='gestion_servicios.cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones_equipo', to='gestion_servicios.equipo')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to='gestion_servicios.tecnico')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('serie_imei', models.CharField(help_text='Clave única para identificar el equipo.', max_length=100, unique=True, verbose_name='Nro. Serie / IMEI')),
                ('modelo', models.CharField(help_text='Ej. iPhone 12, XPS 13', max_length=100, verbose_name='Modelo')),
                ('accesorios', models.TextField(blank=True, verbose_name='Accesorios Entregados')),
                ('estado_general', models.TextField(blank=True, verbose_name='Estado General y Estético')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_servicios.marca', verbose_name='Marca')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_servicios.tipoequipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleRepuestoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Utilizada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta Unitario')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_repuestos', to='gestion_servicios.reparacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_reparaciones', to='gestion_servicios.repuesto')),
            ],
            options={
                'verbose_name': 'Repuesto en Reparación',
                'verbose_name_plural': 'Repuestos en Reparaciones',
                'unique_together': {('reparacion', 'repuesto')},
            },
        ),
    ]
