# Generated by Django 5.2.6 on 2025-10-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IMEI'),
        ),
    ]
